# Generated by Django 6.0.3 on 2026-03-22 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('budget', 'Budget'), ('quality', 'Quality')], default='quality', max_length=20)),
                ('difficulty', models.CharField(choices=[('c1_low', 'C1 low'), ('c1_mid', 'C1 mid'), ('c1_high', 'C1 high')], default='c1_mid', max_length=20)),
                ('timer_enabled', models.BooleanField(default=True)),
                ('ruoe_timer_minutes', models.PositiveIntegerField(default=90)),
                ('writing_timer_minutes', models.PositiveIntegerField(default=90)),
                ('uk_spelling', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('selected_parts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_code', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8'), ('W1', 'W1'), ('W2', 'W2')], max_length=2)),
                ('section_type', models.CharField(choices=[('ruoe', 'Reading and Use of English'), ('writing', 'Writing')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('submitted', 'Submitted')], default='pending', max_length=20)),
                ('generator_version', models.CharField(blank=True, default='', max_length=100)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('answer_key_json', models.JSONField(blank=True, default=dict)),
                ('raw_model_output', models.TextField(blank=True, default='')),
                ('prompt_log_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('results_json', models.JSONField(blank=True, default=list)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.examsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['user'], name='exams_exam_user_id_603a39_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_exam_status_7a27f8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_at'], name='exams_exam_created_d6563d_idx'),
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['status'], name='exams_exams_status_14e163_idx'),
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['part_code'], name='exams_exams_part_co_0577ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(fields=('exam', 'part_code'), name='unique_exam_part_code'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['user'], name='exams_secti_user_id_54a79e_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['submitted_at'], name='exams_secti_submitt_086746_idx'),
        ),
    ]
